name: GitHub Pages Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run tests and lint code
      run: |
        npm test
        npm run lint --if-present
    - name: Deploy to Github Pages
      run: npm run deploy
